infrastructure/refund_status.tf, infrastructure/variables.tf
=> Fixing few terraform syntax error

Jenkinsfile_CNP, build.gradle, config/pmd/ruleset.xml, cve-resolution-strategy.gradle, src/functionalTest/java/uk/gov/hmcts/reform/refunds/RootFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/refunds/config/IdamApi.java, src/functionalTest/java/uk/gov/hmcts/reform/refunds/config/IdamService.java, src/functionalTest/java/uk/gov/hmcts/reform/refunds/config/Oauth2.java, src/functionalTest/java/uk/gov/hmcts/reform/refunds/config/OneTimePasswordFactory.java, src/functionalTest/java/uk/gov/hmcts/reform/refunds/config/S2sApi.java, src/functionalTest/java/uk/gov/hmcts/reform/refunds/config/S2sTokenService.java, src/functionalTest/java/uk/gov/hmcts/reform/refunds/config/TestConfigProperties.java, src/functionalTest/java/uk/gov/hmcts/reform/refunds/config/TestContextConfiguration.java, src/functionalTest/java/uk/gov/hmcts/reform/refunds/config/TokenExchangeRequest.java, src/functionalTest/java/uk/gov/hmcts/reform/refunds/config/User.java, src/functionalTest/java/uk/gov/hmcts/reform/refunds/config/ValidUser.java, src/functionalTest/resources/application-test.yaml
=> functional tests

src/functionalTest/java/uk/gov/hmcts/reform/refunds/RootFunctionalTest.java, src/main/java/uk/gov/hmcts/reform/refunds/controllers/RootController.java, src/main/java/uk/gov/hmcts/reform/refunds/services/RefundsDomainService.java, src/main/java/uk/gov/hmcts/reform/refunds/services/RefundsDomainServiceImpl.java
=> changed services names

src/functionalTest/resources/application-test.yaml, src/test/resources/application-test.yaml
=> test user password removed

infrastructure/main.tf
=> updating refunds api backend url

infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/ithc.tfvars, infrastructure/perftest.tfvars, infrastructure/template/api-policy.xml
=> adding new thumbprint

src/main/java/uk/gov/hmcts/reform/refunds/dtos/requests/RefundRequest.java, src/main/java/uk/gov/hmcts/reform/refunds/mappers/ReconciliationProviderMapper.java, src/main/java/uk/gov/hmcts/reform/refunds/model/Refund.java, src/main/java/uk/gov/hmcts/reform/refunds/services/RefundsServiceImpl.java, src/main/resources/db/changelog/db.changelog-0.1.yaml, src/test/java/uk/gov/hmcts/reform/refunds/controllers/RefundControllerTest.java
=> fee id implementation

src/main/java/uk/gov/hmcts/reform/refunds/config/security/SpringSecurityConfiguration.java, src/main/java/uk/gov/hmcts/reform/refunds/controllers/RefundsController.java, src/main/java/uk/gov/hmcts/reform/refunds/dtos/responses/RejectionReasonResponse.java, src/main/java/uk/gov/hmcts/reform/refunds/exceptions/RetrospectiveRemissionNotFoundException.java, src/main/java/uk/gov/hmcts/reform/refunds/services/RefundsService.java, src/main/java/uk/gov/hmcts/reform/refunds/services/RefundsServiceImpl.java, src/test/java/uk/gov/hmcts/reform/refunds/controllers/RefundControllerTest.java
=> Rejection reasons

charts/ccpay-refunds-api/Chart.yaml, charts/ccpay-refunds-api/values.preview.template.yaml, charts/ccpay-refunds-api/values.yaml, src/main/java/uk/gov/hmcts/reform/refunds/config/ServiceAuthTokenConfiguration.java, src/main/java/uk/gov/hmcts/reform/refunds/services/PaymentServiceImpl.java, src/main/java/uk/gov/hmcts/reform/refunds/services/ReconciliationProviderServiceImpl.java, src/test/java/uk/gov/hmcts/reform/refunds/controllers/RefundControllerTest.java
=> changes for payment connection

src/main/java/uk/gov/hmcts/reform/refunds/mappers/ReconciliationProviderMapper.java, src/main/java/uk/gov/hmcts/reform/refunds/services/RefundsServiceImpl.java, src/main/resources/application-local.yaml, src/main/resources/db/changelog/db.changelog-0.7.yaml, src/main/resources/db/changelog/db.changelog-master.xml, src/main/resources/db/changelog/db.changelog-master.yaml, src/test/java/uk/gov/hmcts/reform/refunds/controllers/RefundControllerTest.java
=> Retro refund reason add

src/main/java/uk/gov/hmcts/reform/refunds/services/RefundsServiceImpl.java, src/test/java/uk/gov/hmcts/reform/refunds/controllers/RefundControllerTest.java
=> feeid validation added

charts/ccpay-refunds-api/Chart.yaml, config/owasp/suppressions.xml, cve-resolution-strategy.gradle, infrastructure/main.tf
=> changes for bringing the  s2s secret to refunds key vault

infrastructure/state.tf
=> added azurerd provider configuration

charts/ccpay-refunds-api/values.preview.template.yaml, charts/ccpay-refunds-api/values.yaml, src/main/java/uk/gov/hmcts/reform/refunds/services/PaymentServiceImpl.java
=> s2s changes

charts/ccpay-refunds-api/Chart.yaml, charts/ccpay-refunds-api/values.preview.template.yaml, charts/ccpay-refunds-api/values.yaml, src/test/java/uk/gov/hmcts/reform/refunds/controllers/RootControllerTest.java
=> Adding secrets changes

charts/ccpay-refunds-api/Chart.yaml, charts/ccpay-refunds-api/values.preview.template.yaml, charts/ccpay-refunds-api/values.yaml
=> Liberata config chart

charts/ccpay-refunds-api/Chart.yaml, charts/ccpay-refunds-api/values.preview.template.yaml, charts/ccpay-refunds-api/values.yaml
=> ContextStartListener changes added

src/main/resources/application-local.yaml, src/main/resources/application.yaml, src/smokeTest/resources/application-smoke.yaml, src/test/resources/application-test.yaml
=> removed the sen info

src/main/java/uk/gov/hmcts/reform/refunds/controllers/RefundsController.java, src/test/java/uk/gov/hmcts/reform/refunds/controllers/RefundControllerLock.java, src/test/java/uk/gov/hmcts/reform/refunds/controllers/RefundControllerTest.java
=> feature lock added

src/functionalTest/resources/application-functional.yaml, src/main/resources/application-local.yaml, src/smokeTest/resources/application-smoke.yaml
=> removed sensitive info

build.gradle, charts/ccpay-refunds-api/values.preview.template.yaml, src/functionalTest/java/uk/gov/hmcts/reform/refunds/functional/RefundsApproverJourneyFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/refunds/functional/fixture/RefundsFixture.java, src/functionalTest/java/uk/gov/hmcts/reform/refunds/functional/request/ContactDetails.java, src/functionalTest/java/uk/gov/hmcts/reform/refunds/functional/service/PaymentTestService.java, src/functionalTest/resources/application-functional.yaml, src/main/java/uk/gov/hmcts/reform/refunds/model/ContactDetails.java, src/test/java/uk/gov/hmcts/reform/refunds/controllers/RefundControllerTest.java, src/test/java/uk/gov/hmcts/reform/refunds/service/RefundServiceImplTest.java
=> PAY-5360 Removed template_id

charts/ccpay-refunds-api/Chart.yaml, charts/ccpay-refunds-api/values.yaml
=> Pay 5368 bump up chart

src/main/java/uk/gov/hmcts/reform/refunds/dtos/responses/RefundDto.java, src/main/java/uk/gov/hmcts/reform/refunds/mapper/RefundResponseMapper.java
…eview Refund screen
```
[ ] Yes
[ ] No
```
=> PAY-5364 added contact details in GET /refund API response body

charts/ccpay-refunds-api/Chart.yaml, charts/ccpay-refunds-api/values.preview.template.yaml, charts/ccpay-refunds-api/values.yaml
=> 5347 chart update

config/owasp/suppressions.xml, cve-resolution-strategy.gradle, src/main/java/uk/gov/hmcts/reform/refunds/dtos/requests/RefundStatusUpdateRequest.java, src/main/java/uk/gov/hmcts/reform/refunds/services/RefundStatusServiceImpl.java, src/main/java/uk/gov/hmcts/reform/refunds/services/RefundsServiceImpl.java
- Updated logic for displaying Refunds list
```
[ ] Yes
[ ] No
```
=> Production issue fix

src/main/java/uk/gov/hmcts/reform/refunds/dtos/responses/RefundDto.java, src/main/java/uk/gov/hmcts/reform/refunds/mapper/RefundResponseMapper.java
=> Added feeIds to RefundDto

charts/ccpay-refunds-api/Chart.yaml, charts/ccpay-refunds-api/values.preview.template.yaml, charts/ccpay-refunds-api/values.yaml
=> Chart bump up

build.gradle, config/owasp/suppressions.xml
=> CVE fixes 1 apr 2022

Jenkinsfile_nightly, build.gradle, config/owasp/suppressions.xml, security.sh
=> Pay 5519 onboading jenkins dashboard

build.gradle, config/owasp/suppressions.xml
- Fixed CVE issue CVE-2022-0839
- Suppressed CVE-2020-36518 & CVE-2022-21724
```
[ ] Yes
[ ] No
```
=> CVE issue Fixes

Jenkinsfile_nightly
=> PAY-5519 corrected test url for nightly build

config/owasp/suppressions.xml
=> CVE Fix 11-Apr-2022

build.gradle
=> Fixed CVE-2022-25647

Jenkinsfile_nightly, build.gradle, charts/ccpay-refunds-api/Chart.yaml, config/fortify-client.properties, config/owasp/suppressions.xml, src/functionalTest/java/uk/gov/hmcts/reform/refunds/functional/config/IdamService.java, src/test/java/uk/gov/hmcts/reform/refunds/state/RefundStateUtilTest.java
=> Fortify scan fix

config/owasp/suppressions.xml
=> Suppress CVE - CVE-2022-33915

charts/ccpay-refunds-api/Chart.yaml, charts/ccpay-refunds-api/values.preview.template.yaml
=> PAY-5683 Java version upgrade in chart yaml

src/functionalTest/java/uk/gov/hmcts/reform/refunds/functional/RefundsApproverJourneyFunctionalTest.java
=> Ignored tests

Jenkinsfile_CNP, Jenkinsfile_nightly, audit.json, charts/ccpay-refunds-api/values.preview.template.yaml, src/functionalTest/java/uk/gov/hmcts/reform/refunds/functional/RefundsApproverJourneyFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/refunds/functional/service/PaymentTestService.java, src/functionalTest/resources/application-functional.yaml, src/main/java/uk/gov/hmcts/reform/refunds/state/RefundState.java, src/test/java/uk/gov/hmcts/reform/refunds/controllers/RefundControllerTest.java
=> removed cancelled state

charts/ccpay-refunds-api/values.preview.template.yaml, config/owasp/suppressions.xml, cve-resolution-strategy.gradle, security.sh, src/functionalTest/resources/application-functional.yaml
=> testing zap changes in nightly-dev

src/main/java/uk/gov/hmcts/reform/refunds/services/RefundsServiceImpl.java
=> Removed loggers

charts/ccpay-refunds-api/values.preview.template.yaml, config/owasp/suppressions.xml, src/functionalTest/resources/application-functional.yaml
=> Suppressed - CVE-2022-42004, CVE-2022-42003

audit.json, charts/ccpay-refunds-api/values.preview.template.yaml
=> adding new endpoint for security scan

charts/ccpay-refunds-api/values.preview.template.yaml, src/functionalTest/java/uk/gov/hmcts/reform/refunds/functional/RefundsApproverJourneyFunctionalTest.java, src/functionalTest/resources/application-functional.yaml, src/main/java/uk/gov/hmcts/reform/refunds/services/RefundsServiceImpl.java
=> Pay 5769 sonar issue

charts/ccpay-refunds-api/values.preview.template.yaml, cve-resolution-strategy.gradle, src/functionalTest/resources/application-functional.yaml, src/test/java/uk/gov/hmcts/reform/refunds/service/RefundServiceImplTest.java
=> PAY-5620 Fixed Blocker issues from Sonar report

build.gradle, charts/ccpay-refunds-api/values.preview.template.yaml, cve-resolution-strategy.gradle, src/functionalTest/resources/application-functional.yaml
=> upgrade snake yaml

charts/ccpay-refunds-api/values.preview.template.yaml, src/functionalTest/resources/application-functional.yaml, src/main/java/uk/gov/hmcts/reform/refunds/controllers/RefundsController.java, src/main/java/uk/gov/hmcts/reform/refunds/services/RefundsServiceImpl.java
=> PAY-5638 Fixed Critical Sonar Issues

charts/ccpay-refunds-api/values.preview.template.yaml, config/owasp/suppressions.xml, src/functionalTest/resources/application-functional.yaml
=> CVE Suppression Date Update

src/main/java/uk/gov/hmcts/reform/refunds/dtos/responses/RefundDto.java, src/main/java/uk/gov/hmcts/reform/refunds/mapper/RefundResponseMapper.java
=> added reasonCode in response

charts/ccpay-refunds-api/values.preview.template.yaml, src/functionalTest/java/uk/gov/hmcts/reform/refunds/functional/RefundsApproverJourneyFunctionalTest.java, src/functionalTest/resources/application-functional.yaml, src/main/java/uk/gov/hmcts/reform/refunds/services/NotificationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/refunds/services/RefundStatusServiceImpl.java, src/test/java/uk/gov/hmcts/reform/refunds/controllers/RefundControllerTest.java
=> PAY-5766 Hardcard token

charts/ccpay-refunds-api/values.preview.template.yaml, src/functionalTest/resources/application-functional.yaml, src/main/java/uk/gov/hmcts/reform/refunds/dtos/responses/ContactDetailsDto.java, src/main/java/uk/gov/hmcts/reform/refunds/mapper/RefundNotificationMapper.java, src/main/java/uk/gov/hmcts/reform/refunds/mapper/RefundResponseMapper.java, src/main/java/uk/gov/hmcts/reform/refunds/services/NotificationService.java, src/main/java/uk/gov/hmcts/reform/refunds/services/NotificationServiceImpl.java, src/main/java/uk/gov/hmcts/reform/refunds/services/RefundStatusServiceImpl.java, src/main/java/uk/gov/hmcts/reform/refunds/utils/RefundsUtil.java, src/test/java/uk/gov/hmcts/reform/refunds/controllers/RefundControllerTest.java, src/test/java/uk/gov/hmcts/reform/refunds/mappers/RefundNotificationMapperTest.java, src/test/java/uk/gov/hmcts/reform/refunds/service/NotificationServiceImplTest.java
=> PAY-5873 remove Unable to apply refund to Card

src/main/java/uk/gov/hmcts/reform/refunds/services/RefundsServiceImpl.java, src/test/java/uk/gov/hmcts/reform/refunds/service/RefundServiceImplTest.java
=> add refud amount for all status except rejected

charts/ccpay-refunds-api/values.preview.template.yaml, config/owasp/suppressions.xml, cve-resolution-strategy.gradle, src/functionalTest/resources/application-functional.yaml
=> CVE fix 11012023

src/main/java/uk/gov/hmcts/reform/refunds/config/security/SpringSecurityConfiguration.java
=> Refunds v2 job

Jenkinsfile_CNP, Jenkinsfile_nightly, charts/ccpay-refunds-api/Chart.yaml
=> Update jenkins after

charts/ccpay-refunds-api/values.preview.template.yaml, config/owasp/suppressions.xml, src/functionalTest/resources/application-functional.yaml
=> suppressing cve pending new version of jackson-core

charts/ccpay-refunds-api/Chart.yaml, charts/ccpay-refunds-api/values.preview.template.yaml, cve-resolution-strategy.gradle, src/functionalTest/resources/application-functional.yaml
=> upgrading java chart to 4.0.12 and commons fileupload to 1.5

charts/ccpay-refunds-api/values.preview.template.yaml, config/owasp/suppressions.xml, src/functionalTest/resources/application-functional.yaml, src/main/java/uk/gov/hmcts/reform/refunds/services/RefundsServiceImpl.java
=> Resubmit refund reason fix

charts/ccpay-refunds-api/values.preview.template.yaml, config/owasp/suppressions.xml, src/functionalTest/resources/application-functional.yaml
=> CVE issue fix

src/main/resources/db/changelog/db.changelog-0.7.yaml, src/main/resources/db/changelog/db.changelog-0.8.yaml, src/main/resources/db/changelog/db.changelog-0.9.yaml
=> db changes to added new change sets

src/main/resources/db/changelog/db.changelog-0.8.yaml
=> db changes for refund_status

src/main/resources/db/changelog/db.changelog-0.8.yaml
=> db changes for build pass

charts/ccpay-refunds-api/Chart.yaml, charts/ccpay-refunds-api/values.preview.template.yaml, charts/ccpay-refunds-api/values.yaml, src/functionalTest/resources/application-functional.yaml
=> added templated id in values.yaml

audit.json, functional-output/README.md
https://tools.hmcts.net/jira/browse/PAY-4884
Fix to ZAP Security tests.
```
[ ] Yes
[x] No
```
=> PAY-4884: Fix for security tests.

src/functionalTest/java/uk/gov/hmcts/reform/refunds/functional/PaymentFailureReportFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/refunds/functional/RefundsApproverJourneyFunctionalTest.java
=> added ignore

src/functionalTest/java/uk/gov/hmcts/reform/refunds/functional/PaymentFailureReportFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/refunds/functional/RefundsApproverJourneyFunctionalTest.java
=> revert ft ignore

audit.json, src/functionalTest/java/uk/gov/hmcts/reform/refunds/functional/PaymentFailureReportFunctionalTest.java, src/functionalTest/java/uk/gov/hmcts/reform/refunds/functional/RefundsApproverJourneyFunctionalTest.java
=> remove ignore from ft

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PAY-4884
Suppression for CVE with no fix available.
```
[ ] Yes
[x] No
```
=> Suppression for cve with no fix available.

audit.json, charts/ccpay-refunds-api/Chart.yaml, charts/ccpay-refunds-api/values.preview.template.yaml, src/functionalTest/resources/application-functional.yaml, src/smokeTest/resources/application-smoke.yaml
https://tools.hmcts.net/jira/browse/PAY-5997
Update to use platform.hmcts.net for staging and preview URLs.
```
[ ] Yes
[x] No
```
=> PAY-5997: Update references to use platform.hmcts.net

config/owasp/suppressions.xml
CVE-2023-20883 suppression
```
[ ] Yes
[X] No
```
=> CVE-2023-20883 suppression

config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PAY-6040
CVE Suppression for pipeline fix
```
[ ] Yes
[X] No
```
=> CVE-2023-2976 suppression

charts/ccpay-refunds-api/Chart.yaml, charts/ccpay-refunds-api/values.yaml
https://tools.hmcts.net/jira/browse/PAY-6359
Set chart dependency apps to false in values.yaml.
```
[ ] Yes
[x] No
```
=> PAY-6359: Set Chart depend apps to false.

Jenkinsfile_CNP, Jenkinsfile_nightly, charts/ccpay-refunds-api/Chart.yaml, charts/ccpay-refunds-api/values.preview.template.yaml, src/functionalTest/resources/application-functional.yaml
https://tools.hmcts.net/jira/browse/PAY-5466
Update so that PR builds dependancy apps.
```
[ ] Yes
[x] No
```
=> Build dependancy apps in Preview again.

src/functionalTest/java/uk/gov/hmcts/reform/refunds/functional/RefundsApproverJourneyFunctionalTest.java
https://tools.hmcts.net/jira/browse/PAY-5466
Disable negative test, will fix through JIRA.
```
[ ] Yes
[x] No
```
=> Refunds FT update nagative_create_refund_without_service_role

build.gradle, config/owasp/suppressions.xml
https://tools.hmcts.net/jira/browse/PAY-6443
Add CVE fix and suppression.
```
[ ] Yes
[x] No
```
=> PAY-6443: Add CVE fix and suppression

config/owasp/suppressions.xml
PAY_6471
First fix attempt
```
[ ] Yes
[ x ] No
```
=> fix attempt PAY_6471

config/owasp/suppressions.xml
PAY-1849CVE
Fix for CVE-2023-41080
```
[ ] Yes
[ x ] No
```
=> fix for VE-2023-41080

config/owasp/suppressions.xml
Fix for CVE-2023-41080
PAY_6475
```
[ ] Yes
[ x ] No
```
=> Fix for CVE-2023-41080

.github/renovate.json
PAY-6546: Renovate
[PAY-6546] (https://tools.hmcts.net/jira/browse/PAY-6546).
=>  PAY-6546: Renovate

config/owasp/suppressions.xml
4 suppressions. The tomcat ones need a Spring Boot upgrade on next round of upgrades.
The http one has a separate ticket - resolution unknown as yet.
https://tools.hmcts.net/jira/browse/PAY-66
```
[ ] Yes
[ X] No
```
=> PAY-6619 CVE suppressions

charts/ccpay-refunds-api/Chart.yaml, charts/ccpay-refunds-api/values.yaml
PAY_6611
Version update
```
[ ] Yes
[ x ] No
```
=> version update

build.gradle, infrastructure/aat.tfvars, infrastructure/demo.tfvars, infrastructure/ithc.tfvars, infrastructure/main.tf, infrastructure/perftest.tfvars, infrastructure/prod.tfvars, infrastructure/provider.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/PAY-6571
Creating of flexible server
```
[ ] Yes
[X] No
```
=> PAY-6571-Flexible-Server-Setup

infrastructure/main.tf
PAY-6571
remove of flexible server
```
[ ] Yes
[X] No
```
=> PAY-6571-remove flexible server

infrastructure/main.tf
PAY-6571
recreate flxible server
```
[ ] Yes
[x] No
```
=> PAY-6571-recreate flexible server

charts/ccpay-refunds-api/Chart.yaml, charts/ccpay-refunds-api/values.yaml
PAY-6571
Amended the secrets
```
[ ] Yes
[x] No
```
=> PAY-6571 amend the secrets

README.md
=> PAY-6571: Testing FT

README.md
https://tools.hmcts.net/jira/browse/PAY-6571
```
[ ] Yes
[x] No
```
=> PAY-6571: Refresh refunds apps

charts/ccpay-refunds-api/Chart.yaml
https://tools.hmcts.net/jira/browse/PAY-6571
```
[ ] Yes
[x] No
```
=> PAY-6571: Update Charts Payment Version

charts/ccpay-refunds-api/Chart.yaml, charts/ccpay-refunds-api/values.aat.template.yaml
https://tools.hmcts.net/jira/browse/PAY-6571
Update secrets for AAT.
```
[ ] Yes
[x] No
```
=> PAY-6571: Update secrets for AAT.

README.md, src/main/java/uk/gov/hmcts/reform/refunds/services/RefundsServiceImpl.java, src/test/java/uk/gov/hmcts/reform/refunds/service/RefundServiceImplTest.java
https://tools.hmcts.net/jira/browse/PAY-6694
Updated to provide a 'User not found' message for refunds which have had the created by user deleted.
```
[ ] Yes
[x] No
```
=> PAY-6694: Strategic fix for User not found refunds list

charts/ccpay-refunds-api/Chart.yaml, infrastructure/main.tf
https://tools.hmcts.net/jira/browse/PAY-6701
Force access to flexible server db
```
[ ] Yes
[X] No
```
=> PAY-6701 Force Access to flexible DB

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/PAY-6594
Remove read only trigger.
```
[ ] Yes
[x] No
```
=> PAY-6594: Remove trigger for old DB

build.gradle, infrastructure/main.tf
https://tools.hmcts.net/jira/browse/PAY-6717
Amend secrets in main.tf
```
[ ] Yes
[x] No
```
=> PAY-6717 amend secrets

charts/ccpay-refunds-api/Chart.yaml, charts/ccpay-refunds-api/values.yaml, infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/PAY-6659
Decommission v11 refunds database
```
[ ] Yes
[x] No
```
=> PAY-6659-decommission v11 database

README.md
[PAY-6889](https://tools.hmcts.net/jira/browse/PAY-6889)
whitespace added to kick off a pieline build
```
[ ] Yes
[x] No
```
=> PAY-6889 create build for pipeline

cve-resolution-strategy.gradle, src/main/java/uk/gov/hmcts/reform/refunds/services/RefundStatusServiceImpl.java
Reverts hmcts/ccpay-refunds-app#542
=> Revert "PAY-6925"

src/main/java/uk/gov/hmcts/reform/refunds/services/RefundStatusServiceImpl.java
https://tools.hmcts.net/jira/browse/PAY-6925
Amended the liberata refund status history note
```
[ ] Yes
[x] No
```
=> PAY-6925_change

.github/workflows/stale.yml
https://tools.hmcts.net/jira/browse/PAY-6981
https://tools.hmcts.net/jira/browse/PAY-6982
Auto close bot for PR addition of stale.yml file and helm update
```
[ ] Yes
[ X ] No
```
=> PAY-6982  Auto close bot for PR addition of stale.yml file and helm update

charts/ccpay-refunds-api/Chart.yaml
https://tools.hmcts.net/jira/browse/PAY-6982
Update Java chart version to 5.2.0
```
[ ] Yes
[x] No
```
=> PAY-6982: Update Java chart version

config/owasp/suppressions.xml, cve-resolution-strategy.gradle
https://tools.hmcts.net/jira/browse/PAY-6083
```
[ ] Yes
[ ] No
```
=> PAY-6083: Fix CVE-2022-1471

README.md, build.gradle, charts/ccpay-refunds-api/values.preview.template.yaml
https://tools.hmcts.net/jira/browse/PAY-7302
Fix master from being disabled in Jenkins
```
[ ] Yes
[x] No
```
=> PAY-7302: Fix master from being disabled in Jenkins

.github/workflows/ci.yml, .gitignore, Dockerfile, build.gradle
https://tools.hmcts.net/jira/browse/CME-62
```
[ ] Yes
[ ] No
```
=> CME-62: Java 21

charts/ccpay-refunds-api/Chart.yaml
https://tools.hmcts.net/jira/browse/CME-421
```
[ ] Yes
[ ] No
```
=> CME-421: OCI image

infrastructure/main.tf
https://tools.hmcts.net/jira/browse/PAY-7766
removal of azure extension plpgsql
```
[ ] Yes
[x] No
```
=> PAY-7766 removal of azure extension plpgsql

infrastructure/main.tf, infrastructure/variables.tf
https://tools.hmcts.net/jira/browse/CME-126
Added action group to alert about high database usage.
```
[ ] Yes
[x] No
```
=> CME-126 add db monitoring action group

src/functionalTest/java/uk/gov/hmcts/reform/refunds/functional/RefundsApproverJourneyFunctionalTest.java, src/main/java/uk/gov/hmcts/reform/refunds/services/RefundStatusServiceImpl.java, src/test/java/uk/gov/hmcts/reform/refunds/controllers/RefundControllerTest.java
https://tools.hmcts.net/jira/browse/PAY-7934
remove RefundWhenContacted
```
[ ] Yes
[X] No
```
=> PAY-7934 remove RefundWhenContacted
